[package]
name = "cheatsheet_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
man = "0.3.0"
serde = "1.0.201"
serde_yaml = "0.9.34"
